In [5]:
import pandas as pd

In [4]:
df = pd.read_csv(
    r'C:\Users\lamba\OneDrive\Documents\customer_sales_analysis\customer_shopping_project\customer_shopping_behavior.csv'
)

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [6]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [8]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [9]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [11]:
df['Review Rating'] = (
    df.groupby('Category')['Review Rating']
      .transform(lambda x: x.fillna(x.median()))
)

In [12]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [13]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

df = df.rename(
    columns={'purchase_amount_(usd)': 'purchase_amount'}
)

In [14]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [15]:
bins = [0, 18, 40, 60, float('inf')]

labels = [
    'Young',
    'Adult',
    'Middle Aged',
    'Senior Citizen'
]

df['age_group'] = pd.cut(
    df['age'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [16]:
df[['age', 'age_group']].head(10)

   age       age_group
0   55     Middle Aged
1   19           Adult
2   50     Middle Aged
3   21           Adult
4   45     Middle Aged
5   46     Middle Aged
6   63  Senior Citizen
7   27           Adult
8   26           Adult
9   57     Middle Aged

In [26]:
frequency_mapping = {
    'Weekly': 7,
    'Fortnightly': 14,
    'Bi-Weekly': 14,
    'Monthly': 30,
    'Every 3 Months': 90,
    'Quarterly': 90,
    'Annually': 365
}

df['purchase_frequency_days'] = (
    df['frequency_of_purchases'].map(frequency_mapping)
)

In [34]:
df[
    ['frequency_of_purchases', 'purchase_frequency_days']
].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [35]:
df[['frequency_of_purchases', 'purchase_frequency_days']].drop_duplicates().sort_values('purchase_frequency_days')

   frequency_of_purchases  purchase_frequency_days
2                  Weekly                        7
0             Fortnightly                       14
10              Bi-Weekly                       14
15                Monthly                       30
20         Every 3 Months                       90
6               Quarterly                       90
4                Annually                      365

In [39]:
df.columns.tolist()

['customer_id',
 'age',
 'gender',
 'item_purchased',
 'category',
 'purchase_amount',
 'location',
 'size',
 'color',
 'season',
 'review_rating',
 'subscription_status',
 'shipping_type',
 'discount_applied',
 'previous_purchases',
 'payment_method',
 'frequency_of_purchases',
 'age_group',
 'purchase_frequency_days']

In [41]:
[col for col in df.columns if 'discount' in col or 'promo' in col]

['discount_applied']

In [22]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [42]:
df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount            0
location                   0
size                       0
color                      0
season                     0
review_rating              0
subscription_status        0
shipping_type              0
discount_applied           0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
age_group                  0
purchase_frequency_days    0
dtype: int64

In [44]:
print("Duplicate rows:", df.duplicated().sum())
df.head()

Duplicate rows: 0

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle Aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle Aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle Aged,365

In [45]:
df['frequency_of_purchases'].value_counts(dropna=False)

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [46]:
df['purchase_frequency_days'].isnull().sum()

np.int64(0)

In [47]:
df[['frequency_of_purchases', 'purchase_frequency_days']].drop_duplicates().sort_values('purchase_frequency_days')

   frequency_of_purchases  purchase_frequency_days
2                  Weekly                        7
0             Fortnightly                       14
10              Bi-Weekly                       14
15                Monthly                       30
20         Every 3 Months                       90
6               Quarterly                       90
4                Annually                      365

In [50]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [51]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   str
 3   item_purchased           3900 non-null   str
 4   category                 3900 non-null   str
 5   purchase_amount          3900 non-null   int64
 6   location                 3900 non-null   str
 7   size                     3900 non-null   str
 8   color                    3900 non-null   str
 9   season                   3900 non-null   str
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   str
 12  shipping_type            3900 non-null   str
 13  discount_applied         3900 non-null   str
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   str
 16  frequency_of_purchases   3900 non-null   str
 17  age_group                3900 non-null   category
 18  purchase_frequency_days  3900 non-null   int64
dtypes: category(1), float64(1), int64(5), str(12)
memory usage: 552.6 KB

In [52]:
df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount            0
location                   0
size                       0
color                      0
season                     0
review_rating              0
subscription_status        0
shipping_type              0
discount_applied           0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
age_group                  0
purchase_frequency_days    0
dtype: int64

In [53]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [54]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle Aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle Aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle Aged,365

In [55]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in C:\Users\lamba\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in C:\Users\lamba\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\Users\lamba\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.4)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\lamba\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.16.0)

In [56]:
from sqlalchemy import create_engine

In [62]:
username = "postgres"
password = 0000
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

print("PostgreSQL engine created.")

PostgreSQL engine created.

In [66]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("SELECT current_database();"))
    print("Connected to:", result.scalar())

Connected to: customer_behavior

In [67]:
table_name = "customer"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(
    f"Data successfully loaded into table '{table_name}' "
    f"in database '{database}'."
)

Data successfully loaded into table 'customer' in database 'customer_behavior'.

In [68]:
query = """
SELECT *
FROM customer
LIMIT 5;
"""

pd.read_sql(query, engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle Aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle Aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle Aged,365

In [70]:
query = """
SELECT COUNT(*) AS total_customers
FROM customer;
"""

pd.read_sql(query, engine)

   total_customers
0             3900

In [71]:
query = """
SELECT SUM(purchase_amount) AS total_revenue
FROM customer;
"""

pd.read_sql(query, engine)

   total_revenue
0       233081.0

In [72]:
query = """
SELECT
    category,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY category
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, engine)

      category  total_revenue
0     Clothing       104264.0
1  Accessories        74200.0
2     Footwear        36093.0
3    Outerwear        18524.0

In [73]:
query = """
SELECT
    gender,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
GROUP BY gender
ORDER BY avg_purchase_amount DESC;
"""

pd.read_sql(query, engine)

   gender  avg_purchase_amount
0  Female                60.25
1    Male                59.54

In [74]:
query = """
SELECT
    age_group,
    COUNT(*) AS total_customers,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, engine)

        age_group  total_customers  total_revenue
0           Adult             1605        96333.0
1     Middle Aged             1503        89445.0
2  Senior Citizen              723        43164.0
3           Young               69         4139.0

In [75]:
query = """
SELECT
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY item_purchased
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

  item_purchased  total_purchases  total_revenue
0         Blouse              171        10410.0
1          Shirt              169        10332.0
2          Dress              166        10320.0
3          Pants              171        10090.0
4        Jewelry              171        10010.0
5     Sunglasses              161         9649.0
6           Belt              161         9635.0
7          Scarf              157         9561.0
8        Sweater              164         9462.0
9         Shorts              157         9433.0

In [76]:
query = """
SELECT
    subscription_status,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, engine)

  subscription_status  total_customers  avg_purchase_amount  total_revenue
0                  No             2847                59.87       170436.0
1                 Yes             1053                59.49        62645.0

In [77]:
query = """
SELECT
    discount_applied,
    COUNT(*) AS total_purchases,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY discount_applied
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, engine)

  discount_applied  total_purchases  avg_purchase_amount  total_revenue
0               No             2223                60.13       133670.0
1              Yes             1677                59.28        99411.0

In [78]:
query = """
SELECT
    frequency_of_purchases,
    purchase_frequency_days,
    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
GROUP BY frequency_of_purchases, purchase_frequency_days
ORDER BY purchase_frequency_days;
"""

pd.read_sql(query, engine)

,frequency_of_purchases,purchase_frequency_days,total_customers,avg_purchase_amount
0,Weekly,7,539,58.97
1,Bi-Weekly,14,547,60.69
2,Fortnightly,14,542,59.05
3,Monthly,30,553,59.33
4,Quarterly,90,563,59.98
5,Every 3 Months,90,584,60.08
6,Annually,365,572,60.17

In [79]:
query = """
SELECT
    payment_method,
    COUNT(*) AS total_transactions,
    SUM(purchase_amount) AS total_revenue,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
GROUP BY payment_method
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, engine)

  payment_method  total_transactions  total_revenue  avg_purchase_amount
0    Credit Card                 671        40310.0                60.07
1         PayPal                 677        40109.0                59.25
2           Cash                 670        40002.0                59.70
3     Debit Card                 636        38742.0                60.92
4          Venmo                 634        37374.0                58.95
5  Bank Transfer                 612        36544.0                59.71

In [80]:
query = """
SELECT
    location,
    COUNT(*) AS total_purchases,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

        location  total_purchases  total_revenue
0        Montana               96         5784.0
1       Illinois               92         5617.0
2     California               95         5605.0
3          Idaho               93         5587.0
4         Nevada               87         5514.0
5        Alabama               89         5261.0
6       New York               87         5257.0
7   North Dakota               83         5220.0
8  West Virginia               81         5174.0
9       Nebraska               87         5172.0

In [81]:
query = """
SELECT
    customer_id,
    previous_purchases,
    purchase_amount,
    CASE
        WHEN previous_purchases >= 40 THEN 'Loyal Customer'
        WHEN previous_purchases >= 20 THEN 'Regular Customer'
        WHEN previous_purchases >= 10 THEN 'Occasional Customer'
        ELSE 'New Customer'
    END AS customer_segment
FROM customer
ORDER BY previous_purchases DESC;
"""

segments = pd.read_sql(query, engine)

segments.head(10)

   customer_id  previous_purchases  purchase_amount customer_segment
0          858                  50               60   Loyal Customer
1         1633                  50               28   Loyal Customer
2          311                  50               85   Loyal Customer
3         1296                  50               60   Loyal Customer
4         3639                  50               20   Loyal Customer
5         3582                  50               95   Loyal Customer
6         1902                  50               76   Loyal Customer
7         1830                  50               96   Loyal Customer
8         1356                  50               91   Loyal Customer
9         2028                  50               73   Loyal Customer

In [82]:
query = """
SELECT
    CASE
        WHEN previous_purchases >= 40 THEN 'Loyal Customer'
        WHEN previous_purchases >= 20 THEN 'Regular Customer'
        WHEN previous_purchases >= 10 THEN 'Occasional Customer'
        ELSE 'New Customer'
    END AS customer_segment,

    COUNT(*) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount,
    SUM(purchase_amount) AS total_revenue

FROM customer

GROUP BY customer_segment
ORDER BY total_revenue DESC;
"""

pd.read_sql(query, engine)

      customer_segment  total_customers  avg_purchase_amount  total_revenue
0     Regular Customer             1575                59.51        93735.0
1       Loyal Customer              847                60.25        51035.0
2  Occasional Customer              770                58.66        45169.0
3         New Customer              708                60.94        43142.0

In [83]:
from sqlalchemy import text

query = """
ALTER TABLE customer
ADD COLUMN IF NOT EXISTS customer_segment VARCHAR(30);
"""

with engine.begin() as connection:
    connection.execute(text(query))

print("customer_segment column created.")

customer_segment column created.

In [84]:
query = """
UPDATE customer
SET customer_segment =
    CASE
        WHEN previous_purchases >= 40 THEN 'Loyal Customer'
        WHEN previous_purchases >= 20 THEN 'Regular Customer'
        WHEN previous_purchases >= 10 THEN 'Occasional Customer'
        ELSE 'New Customer'
    END;
"""

with engine.begin() as connection:
    connection.execute(text(query))

print("Customer segmentation completed.")

Customer segmentation completed.

In [85]:
query = """
SELECT
    customer_id,
    previous_purchases,
    customer_segment
FROM customer
LIMIT 10;
"""

pd.read_sql(query, engine)

   customer_id  previous_purchases     customer_segment
0         1486                   3         New Customer
1         2690                  47       Loyal Customer
2            1                  14  Occasional Customer
3            2                   2         New Customer
4            3                  23     Regular Customer
5            4                  49       Loyal Customer
6            5                  31     Regular Customer
7            6                  14  Occasional Customer
8            7                  49       Loyal Customer
9            8                  19  Occasional Customer